// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import * as WOS from "./wos";
import type { WaveEnv } from "@/app/waveenv/waveenv";

function callBackendService(waveEnv: WaveEnv, service: string, method: string, args: any[], noUIContext?: boolean): Promise<any> {
    if (waveEnv != null) {
        return waveEnv.callBackendService(service, method, args, noUIContext)
    }
    return WOS.callBackendService(service, method, args, noUIContext);
}

// blockservice.BlockService (block)
export class BlockServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    GetControllerStatus(arg2: string): Promise<BlockControllerRuntimeStatus> {
        return callBackendService(this?.waveEnv, "block", "GetControllerStatus", Array.from(arguments))
    }

    // save the terminal state to a blockfile
    SaveTerminalState(blockId: string, state: string, stateType: string, ptyOffset: number, termSize: TermSize): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "SaveTerminalState", Array.from(arguments))
    }
}

export const BlockService = new BlockServiceType();

// clientservice.ClientService (client)
export class ClientServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    GetClientData(): Promise<Client> {
        return callBackendService(this?.waveEnv, "client", "GetClientData", Array.from(arguments))
    }
}

export const ClientService = new ClientServiceType();

// objectservice.ObjectService (object)
export class ObjectServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // get wave object by oref
    GetObject(oref: string): Promise<WaveObj> {
        return callBackendService(this?.waveEnv, "object", "GetObject", Array.from(arguments))
    }

    // @returns object updates
    UpdateObject(waveObj: WaveObj, returnUpdates: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "UpdateObject", Array.from(arguments))
    }
}

export const ObjectService = new ObjectServiceType();

// windowservice.WindowService (window)
export class WindowServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    CreateWindow(winSize: WinSize, workspaceId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "CreateWindow", Array.from(arguments))
    }
    GetWindow(windowId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "GetWindow", Array.from(arguments))
    }
}

export const WindowService = new WindowServiceType();

// workspaceservice.WorkspaceService (workspace)
export class WorkspaceServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns CloseTabRtn (and object updates)
    CloseTab(workspaceId: string, tabId: string, fromElectron: boolean): Promise<CloseTabRtnType> {
        return callBackendService(this?.waveEnv, "workspace", "CloseTab", Array.from(arguments))
    }

    // @returns tabId (and object updates)
    CreateTab(workspaceId: string, tabName: string, activateTab: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateTab", Array.from(arguments))
    }

    // @returns workspace
    GetWorkspace(workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.waveEnv, "workspace", "GetWorkspace", Array.from(arguments))
    }
}

export const WorkspaceService = new WorkspaceServiceType();

export const AllServiceTypes = {
    "block": BlockServiceType,
    "client": ClientServiceType,
    "object": ObjectServiceType,
    "window": WindowServiceType,
    "workspace": WorkspaceServiceType,
};

export const AllServiceImpls = {
    "block": BlockService,
    "client": ClientService,
    "object": ObjectService,
    "window": WindowService,
    "workspace": WorkspaceService,
};
