// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

package agentsessions

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/wavetermdev/waveterm/pkg/agentobserve"
	"github.com/wavetermdev/waveterm/pkg/wavebase"
)

// Every model call Wave's backend makes is a print-mode run, so the entrypoint field excludes all of
// them at once. The prompt here is deliberately ordinary human text: only the field can reject it,
// which is the whole point of not matching prompt wording.
func TestExtractClaudeSession_DropsPrintModeRuns(t *testing.T) {
	headless := `{"type":"user","cwd":"/repo","entrypoint":"` + agentobserve.HeadlessEntrypoint +
		`","message":{"content":"fix the login bug"}}`
	if s := extractClaudeSession("id1", []string{headless}); s != nil {
		t.Errorf("print-mode transcript should be dropped, got %+v", s)
	}
	interactive := `{"type":"user","cwd":"/repo","entrypoint":"cli","message":{"content":"fix the login bug"}}`
	if s := extractClaudeSession("id2", []string{interactive}); s == nil {
		t.Fatal("interactive session should be kept")
	}
}

// The field can appear on any record, not just the first, so one late marker must still reject the file.
func TestExtractClaudeSession_DropsWhenMarkerIsLate(t *testing.T) {
	lines := []string{
		`{"type":"user","cwd":"/repo","message":{"content":"summarize this"}}`,
		`{"type":"assistant","entrypoint":"` + agentobserve.HeadlessEntrypoint + `","message":{"model":"m"}}`,
	}
	if s := extractClaudeSession("id3", lines); s != nil {
		t.Errorf("a print-mode marker on a later record should still drop the file, got %+v", s)
	}
}

func TestSessionTitle(t *testing.T) {
	cases := []struct {
		name string
		raw  string
		want string
	}{
		{"plain text is untouched", "fix the login bug", "fix the login bug"},
		{
			"a caveat-only message has no content of its own",
			"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>",
			"",
		},
		{
			"real text after the caveat wins",
			"<local-command-caveat>Caveat: boilerplate.</local-command-caveat>\n\nwhat broke the build?",
			"what broke the build?",
		},
		{
			"slash command shows its name and args",
			"<command-message>superpowers:brainstorming</command-message>\n<command-name>/superpowers:brainstorming</command-name>\n<command-args>improve the transcript renderer</command-args>",
			"/superpowers:brainstorming improve the transcript renderer",
		},
		{
			"a bare command name gets its leading slash",
			"<command-name>init</command-name>",
			"/init",
		},
		{
			"a dispatched worker is titled by its goal, not the operator's principles",
			"Work by these principles, and propagate them into every subagent you dispatch:\n- Prefer simple, direct solutions.\n\nYou are running headless with no human at your terminal.\nGoal: split the channel blob into per-run records\nWhen the deliverable is written, commit your work.",
			"split the channel blob into per-run records",
		},
		{
			"the principles preamble without a goal line falls back to the raw text",
			"Work by these principles:\n- Keep it simple.",
			"Work by these principles:\n- Keep it simple.",
		},
		{"empty stays empty", "   ", ""},
	}
	for _, c := range cases {
		if got := sessionTitle(c.raw); got != c.want {
			t.Errorf("%s:\n  got  %q\n  want %q", c.name, got, c.want)
		}
	}
}

// A caveat-only first message must not become the session's title; the scanner walks to the next one.
func TestExtractClaudeSession_SkipsCaveatForTitle(t *testing.T) {
	lines := []string{
		`{"type":"user","cwd":"/repo","entrypoint":"cli","message":{"content":"<local-command-caveat>Caveat: boilerplate.</local-command-caveat>"}}`,
		`{"type":"user","cwd":"/repo","entrypoint":"cli","message":{"content":"why is the donut stale?"}}`,
	}
	s := extractClaudeSession("id4", lines)
	if s == nil {
		t.Fatal("session should be kept")
	}
	if s.Task != "why is the donut stale?" {
		t.Errorf("Task = %q, want the message after the caveat", s.Task)
	}
}

// The directory prune is the cheap first line of defense: the backend's own runs execute in
// wavebase.GetHeadlessAgentDir, so the scanner skips that whole directory without reading a file. The
// transcript planted there looks entirely human, so nothing but the directory skip can exclude it.
func TestScanProvider_SkipsHeadlessDir(t *testing.T) {
	saved := wavebase.DataHome_VarCache
	wavebase.DataHome_VarCache = filepath.Join(t.TempDir(), "data")
	t.Cleanup(func() { wavebase.DataHome_VarCache = saved })

	slug := agentobserve.HeadlessAgentSlug()
	if slug == "" {
		t.Fatal("HeadlessAgentSlug is empty with a data home set")
	}
	root := t.TempDir()
	write := func(dir, task string) {
		if err := os.MkdirAll(filepath.Join(root, dir), 0700); err != nil {
			t.Fatal(err)
		}
		line := `{"type":"user","cwd":"/repo","entrypoint":"cli","message":{"content":"` + task + `"}}`
		if err := os.WriteFile(filepath.Join(root, dir, "s.jsonl"), []byte(line), 0600); err != nil {
			t.Fatal(err)
		}
	}
	write(slug, "fix the login bug")
	write("C--Users-x-repo", "add a retry")

	got := scanProvider(claudeProvider(root), 0, 0)
	if len(got) != 1 {
		t.Fatalf("expected only the real project's session, got %d: %+v", len(got), got)
	}
	if got[0].Task != "add a retry" {
		t.Errorf("wrong session survived: %q", got[0].Task)
	}
}
